[PRIO-148] Added prop to waitToUpload files
start23/react-dropzone-s3-uploader pull request #5
Opened 2017-12-07 20:07 UTC by BenLorantfy

2017-12-07 20:12 UTC, manelpb requested changes

2017-12-07 20:12 UTC, manelpb commented on src/DropzoneS3Uploader.js
> +    if (nextProps.upload !== this.props.upload) {
you can't compare objects like this

2017-12-07 20:12 UTC, manelpb commented on src/DropzoneS3Uploader.js
> +    if (nextProps.upload !== this.props.upload) {
https://stackoverflow.com/questions/1068834/object-comparison-in-javascript

2017-12-07 20:55 UTC, manelpb approved these changes

2017-12-08 05:11 UTC, BenLorantfy commented
Opted to move this to io-web-components instead

2017-12-08 05:11 UTC, closed without merging